{% set version = "0.7.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-clock
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clock_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clock/clock_{{ version }}.tar.gz
  sha256: 0ba21cb6fc73183670135ab95f95558992ebbc1607b673d5302aee072f552e30

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - r-ellipsis                   # [build_platform != target_platform]
    - r-tzdb                       # [build_platform != target_platform]
    - r-cpp11                      # [build_platform != target_platform]
    - r-vctrs                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cpp11 >=0.4.0
    - r-ellipsis >=0.3.1
    - r-rlang >=0.4.10
    - r-tzdb >=0.2.0
    - r-vctrs >=0.3.7
  run:
    - r-base
    - r-cpp11 >=0.4.0
    - r-ellipsis >=0.3.1
    - r-rlang >=0.4.10
    - r-tzdb >=0.2.0
    - r-vctrs >=0.3.7

test:
  commands:
    - $R -e "library('clock')"           # [not win]
    - "\"%R%\" -e \"library('clock')\""  # [win]

about:
  home: https://clock.r-lib.org, https://github.com/r-lib/clock
  license: MIT
  summary: 'Provides a comprehensive library for date-time manipulations using a new family of orthogonal date-time classes (durations, time points, zoned-times, and calendars) that partition responsibilities so that the complexities of time zones are only considered when they are really needed. Capabilities include: date-time
    parsing, formatting, arithmetic, extraction and updating of components, and rounding.'
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
